hard_tabs = false
tab_spaces = 2
max_width = 110
use_small_heuristics = "Max"
newline_style = "Windows"
reorder_imports = true
fn_params_layout = "Tall"
match_arm_leading_pipes = "Preserve"
match_block_trailing_comma = false
remove_nested_parens = true
